"""Curriculum index — a static catalogue of Indian-school topics that
uploaded material can be auto-tagged against.

For each (board, class, subject, chapter) we record:
  - The canonical topic name (in English; translations are derived later)
  - A few sentence-level descriptions of what the chapter covers
  - Pedagogical level (kg / primary / middle / secondary / neet_jee)
  - Subject tags (Physics, Chemistry, Maths, Biology, Civics, etc.)

This file ships the FIRST PASS seed data for the highest-leverage
slice: CBSE Class 6-10 Maths + Science (NEP 2020 mandates Maths + Science
in mother tongue first; everything else follows). State-board variants
and Class 11-12 + competitive-exam syllabi follow in Phase 2.

What this file is NOT:
  - It does NOT host or reproduce NCERT/state-board textbook content.
  - It only carries metadata: chapter titles + a few descriptive
    sentences. This is non-copyrightable factual material. See
    AI_PATHSHALA_BLUEPRINT.md §9 for the legal strategy.

Schema:
    TOPIC = {
        "board": "CBSE" | "ICSE" | "Maharashtra" | "Karnataka" | ...,
        "class": int,           # 6..12
        "subject": str,         # "Science", "Maths", "Social", ...
        "chapter_no": int,
        "chapter_title": str,   # canonical English name
        "level": str,           # padhai/pedagogy.py LEVEL_GUIDANCE key
        "summary": str,         # 1-2 sentences for embedding
        "topics": list[str],    # short concept tags
    }
"""

from __future__ import annotations


CURRICULUM: list[dict] = [
    # ===================== Class 6 =====================
    # Science (NCERT)
    {"board":"CBSE","class":6,"subject":"Science","chapter_no":1,
     "chapter_title":"Components of Food","level":"middle",
     "summary":"Major nutrients in food (carbohydrates, fats, proteins, vitamins, minerals, water) and their roles.",
     "topics":["nutrients","balanced diet","deficiency diseases"]},
    {"board":"CBSE","class":6,"subject":"Science","chapter_no":2,
     "chapter_title":"Sorting Materials Into Groups","level":"middle",
     "summary":"Properties of materials (transparency, hardness, solubility) used to classify them.",
     "topics":["materials","properties","grouping"]},
    {"board":"CBSE","class":6,"subject":"Science","chapter_no":3,
     "chapter_title":"Separation of Substances","level":"middle",
     "summary":"Hand-picking, threshing, winnowing, sieving, sedimentation, decantation, filtration, evaporation.",
     "topics":["mixtures","separation","filtration","evaporation"]},
    {"board":"CBSE","class":6,"subject":"Science","chapter_no":4,
     "chapter_title":"Getting to Know Plants","level":"middle",
     "summary":"Plant parts (roots, stem, leaves, flowers), kinds of plants (herbs, shrubs, trees, climbers, creepers), photosynthesis.",
     "topics":["plants","leaves","photosynthesis","roots"]},
    {"board":"CBSE","class":6,"subject":"Science","chapter_no":5,
     "chapter_title":"Body Movements","level":"middle",
     "summary":"Bones, muscles, joints; movement in different animals (earthworm, snail, cockroach, fish).",
     "topics":["skeleton","joints","muscles","locomotion"]},
    {"board":"CBSE","class":6,"subject":"Science","chapter_no":6,
     "chapter_title":"The Living Organisms and Their Surroundings","level":"middle",
     "summary":"Habitats (aquatic, terrestrial), biotic and abiotic factors, adaptation.",
     "topics":["habitat","adaptation","biotic","abiotic"]},
    {"board":"CBSE","class":6,"subject":"Science","chapter_no":7,
     "chapter_title":"Motion and Measurement of Distances","level":"middle",
     "summary":"SI units, measurement of length, types of motion (rectilinear, circular, periodic).",
     "topics":["measurement","SI units","motion"]},
    {"board":"CBSE","class":6,"subject":"Science","chapter_no":8,
     "chapter_title":"Light, Shadows and Reflections","level":"middle",
     "summary":"Luminous and non-luminous objects, transparent/opaque/translucent, formation of shadows, reflection from mirrors.",
     "topics":["light","shadows","mirrors","reflection"]},
    {"board":"CBSE","class":6,"subject":"Science","chapter_no":9,
     "chapter_title":"Electricity and Circuits","level":"middle",
     "summary":"Simple circuit (battery, switch, bulb), conductors vs insulators.",
     "topics":["circuit","battery","conductor","insulator"]},
    # Maths (Class 6 NCERT)
    {"board":"CBSE","class":6,"subject":"Maths","chapter_no":1,
     "chapter_title":"Knowing Our Numbers","level":"middle",
     "summary":"Place value, Indian and international number systems, estimation, rounding.",
     "topics":["place value","large numbers","estimation"]},
    {"board":"CBSE","class":6,"subject":"Maths","chapter_no":2,
     "chapter_title":"Whole Numbers","level":"middle",
     "summary":"Whole numbers, number line, properties of addition and multiplication, distributivity.",
     "topics":["whole numbers","number line","properties"]},
    {"board":"CBSE","class":6,"subject":"Maths","chapter_no":3,
     "chapter_title":"Playing With Numbers","level":"middle",
     "summary":"Factors, multiples, prime and composite numbers, divisibility rules, HCF, LCM.",
     "topics":["factors","multiples","prime","HCF","LCM"]},
    {"board":"CBSE","class":6,"subject":"Maths","chapter_no":4,
     "chapter_title":"Basic Geometrical Ideas","level":"middle",
     "summary":"Points, lines, angles, triangles, quadrilaterals, polygons, circles.",
     "topics":["geometry","angle","polygon","circle"]},
    {"board":"CBSE","class":6,"subject":"Maths","chapter_no":7,
     "chapter_title":"Fractions","level":"middle",
     "summary":"Proper, improper and mixed fractions; equivalent fractions; addition and subtraction of fractions.",
     "topics":["fractions","equivalent fractions","mixed numbers"]},
    {"board":"CBSE","class":6,"subject":"Maths","chapter_no":11,
     "chapter_title":"Algebra","level":"middle",
     "summary":"Use of variables, simple equations, algebraic expressions.",
     "topics":["algebra","variables","equations"]},

    # ===================== Class 7 =====================
    {"board":"CBSE","class":7,"subject":"Science","chapter_no":1,
     "chapter_title":"Nutrition in Plants","level":"middle",
     "summary":"Photosynthesis, autotrophs and heterotrophs, saprotrophs, symbiosis.",
     "topics":["photosynthesis","autotroph","heterotroph"]},
    {"board":"CBSE","class":7,"subject":"Science","chapter_no":4,
     "chapter_title":"Heat","level":"middle",
     "summary":"Temperature vs heat, thermometer types, transfer of heat (conduction, convection, radiation).",
     "topics":["heat","temperature","conduction","convection","radiation"]},
    {"board":"CBSE","class":7,"subject":"Science","chapter_no":6,
     "chapter_title":"Physical and Chemical Changes","level":"middle",
     "summary":"Reversible and irreversible changes, examples of chemical changes (rusting, burning), crystallisation.",
     "topics":["physical change","chemical change","rusting"]},
    {"board":"CBSE","class":7,"subject":"Maths","chapter_no":1,
     "chapter_title":"Integers","level":"middle",
     "summary":"Operations on integers, properties, multiplication and division of integers.",
     "topics":["integers","operations"]},
    {"board":"CBSE","class":7,"subject":"Maths","chapter_no":4,
     "chapter_title":"Simple Equations","level":"middle",
     "summary":"Forming and solving simple linear equations in one variable.",
     "topics":["linear equation","one variable"]},
    {"board":"CBSE","class":7,"subject":"Maths","chapter_no":11,
     "chapter_title":"Perimeter and Area","level":"middle",
     "summary":"Squares, rectangles, parallelograms, triangles, circumference and area of circle.",
     "topics":["area","perimeter","circle"]},

    # ===================== Class 8 =====================
    {"board":"CBSE","class":8,"subject":"Science","chapter_no":1,
     "chapter_title":"Crop Production and Management","level":"middle",
     "summary":"Agricultural practices, soil preparation, sowing, irrigation, fertilisers and manures.",
     "topics":["agriculture","crops","irrigation"]},
    {"board":"CBSE","class":8,"subject":"Science","chapter_no":4,
     "chapter_title":"Materials: Metals and Non-Metals","level":"middle",
     "summary":"Physical and chemical properties of metals and non-metals, reactivity series, displacement reactions.",
     "topics":["metals","non-metals","reactivity"]},
    {"board":"CBSE","class":8,"subject":"Science","chapter_no":6,
     "chapter_title":"Combustion and Flame","level":"middle",
     "summary":"Types of fuels, conditions necessary for combustion, ignition temperature, types of flames.",
     "topics":["combustion","fuel","ignition","flame"]},
    {"board":"CBSE","class":8,"subject":"Science","chapter_no":11,
     "chapter_title":"Force and Pressure","level":"middle",
     "summary":"Contact and non-contact forces, pressure, atmospheric pressure, pressure in liquids.",
     "topics":["force","pressure","atmospheric pressure"]},
    {"board":"CBSE","class":8,"subject":"Science","chapter_no":15,
     "chapter_title":"Stars and the Solar System","level":"middle",
     "summary":"Celestial objects, planets, satellites, constellations, the solar system.",
     "topics":["solar system","planets","stars","constellations"]},
    {"board":"CBSE","class":8,"subject":"Maths","chapter_no":2,
     "chapter_title":"Linear Equations in One Variable","level":"middle",
     "summary":"Solving linear equations with the variable on both sides, reducing equations to simpler form.",
     "topics":["linear equation","one variable"]},
    {"board":"CBSE","class":8,"subject":"Maths","chapter_no":8,
     "chapter_title":"Comparing Quantities","level":"middle",
     "summary":"Ratios, percentages, profit/loss, discount, simple and compound interest.",
     "topics":["ratio","percentage","interest","discount"]},
    {"board":"CBSE","class":8,"subject":"Maths","chapter_no":11,
     "chapter_title":"Mensuration","level":"middle",
     "summary":"Area of trapezium, general quadrilateral, polygons; surface area and volume of cube, cuboid, cylinder.",
     "topics":["mensuration","area","volume"]},

    # ===================== Class 9 =====================
    {"board":"CBSE","class":9,"subject":"Science","chapter_no":1,
     "chapter_title":"Matter in Our Surroundings","level":"secondary",
     "summary":"States of matter, change of state, evaporation, latent heat.",
     "topics":["matter","states","evaporation","latent heat"]},
    {"board":"CBSE","class":9,"subject":"Science","chapter_no":4,
     "chapter_title":"Structure of the Atom","level":"secondary",
     "summary":"Thomson, Rutherford and Bohr atomic models; atomic number, mass number, isotopes, isobars.",
     "topics":["atom","Bohr model","isotopes","isobars"]},
    {"board":"CBSE","class":9,"subject":"Science","chapter_no":8,
     "chapter_title":"Motion","level":"secondary",
     "summary":"Uniform and non-uniform motion, velocity, acceleration, distance-time and velocity-time graphs, equations of motion.",
     "topics":["motion","velocity","acceleration","equations of motion"]},
    {"board":"CBSE","class":9,"subject":"Science","chapter_no":9,
     "chapter_title":"Force and Laws of Motion","level":"secondary",
     "summary":"Newton's three laws of motion, inertia, momentum, conservation of momentum.",
     "topics":["Newton's laws","force","momentum","inertia"]},
    {"board":"CBSE","class":9,"subject":"Science","chapter_no":10,
     "chapter_title":"Gravitation","level":"secondary",
     "summary":"Universal law of gravitation, free fall, mass vs weight, thrust and pressure, Archimedes principle.",
     "topics":["gravity","gravitation","Archimedes","buoyancy"]},
    {"board":"CBSE","class":9,"subject":"Maths","chapter_no":2,
     "chapter_title":"Polynomials","level":"secondary",
     "summary":"Polynomial in one variable, zeros of a polynomial, remainder theorem, factor theorem, factorisation.",
     "topics":["polynomial","factor theorem","remainder theorem"]},
    {"board":"CBSE","class":9,"subject":"Maths","chapter_no":7,
     "chapter_title":"Triangles","level":"secondary",
     "summary":"Congruence criteria (SSS, SAS, ASA, RHS), properties of isosceles triangle, inequalities in a triangle.",
     "topics":["triangle","congruence","isosceles"]},
    {"board":"CBSE","class":9,"subject":"Maths","chapter_no":10,
     "chapter_title":"Heron's Formula","level":"secondary",
     "summary":"Heron's formula for area of triangle given three sides.",
     "topics":["Heron's formula","area of triangle"]},

    # ===================== Class 10 =====================
    {"board":"CBSE","class":10,"subject":"Science","chapter_no":1,
     "chapter_title":"Chemical Reactions and Equations","level":"secondary",
     "summary":"Types of chemical reactions (combination, decomposition, displacement, double displacement, redox), balancing equations.",
     "topics":["chemical reaction","balanced equation","redox"]},
    {"board":"CBSE","class":10,"subject":"Science","chapter_no":3,
     "chapter_title":"Metals and Non-Metals","level":"secondary",
     "summary":"Physical and chemical properties, ionic and covalent bonding, extraction of metals, corrosion.",
     "topics":["metals","extraction","corrosion","alloy"]},
    {"board":"CBSE","class":10,"subject":"Science","chapter_no":6,
     "chapter_title":"Life Processes","level":"secondary",
     "summary":"Nutrition, respiration, transport, excretion in plants and animals.",
     "topics":["nutrition","respiration","transport","excretion"]},
    {"board":"CBSE","class":10,"subject":"Science","chapter_no":10,
     "chapter_title":"Light - Reflection and Refraction","level":"secondary",
     "summary":"Laws of reflection, spherical mirrors, mirror formula, refraction through glass slab, lens formula.",
     "topics":["reflection","refraction","mirrors","lenses"]},
    {"board":"CBSE","class":10,"subject":"Science","chapter_no":12,
     "chapter_title":"Electricity","level":"secondary",
     "summary":"Electric current, potential difference, Ohm's law, resistance, resistors in series and parallel, heating effect.",
     "topics":["electricity","Ohm's law","resistance","circuits"]},
    {"board":"CBSE","class":10,"subject":"Maths","chapter_no":1,
     "chapter_title":"Real Numbers","level":"secondary",
     "summary":"Euclid's division algorithm, fundamental theorem of arithmetic, irrational numbers, decimal expansions.",
     "topics":["Euclid","irrational","prime factorisation"]},
    {"board":"CBSE","class":10,"subject":"Maths","chapter_no":3,
     "chapter_title":"Pair of Linear Equations in Two Variables","level":"secondary",
     "summary":"Graphical and algebraic methods (substitution, elimination, cross-multiplication) of solving linear equations.",
     "topics":["linear equation","two variables","substitution","elimination"]},
    {"board":"CBSE","class":10,"subject":"Maths","chapter_no":4,
     "chapter_title":"Quadratic Equations","level":"secondary",
     "summary":"Standard form, solution by factorisation and quadratic formula, nature of roots, discriminant.",
     "topics":["quadratic","discriminant","factorisation"]},
    {"board":"CBSE","class":10,"subject":"Maths","chapter_no":8,
     "chapter_title":"Introduction to Trigonometry","level":"secondary",
     "summary":"Trigonometric ratios, identities, ratios of specific angles (0, 30, 45, 60, 90).",
     "topics":["trigonometry","ratios","identities"]},

    # ===================== CBSE Class 11 =====================
    {"board":"CBSE","class":11,"subject":"Physics","chapter_no":2,
     "chapter_title":"Units and Measurements","level":"secondary",
     "summary":"SI base units, dimensions, dimensional analysis, significant figures, errors in measurement.",
     "topics":["SI units","dimensions","significant figures","error"]},
    {"board":"CBSE","class":11,"subject":"Physics","chapter_no":3,
     "chapter_title":"Motion in a Straight Line","level":"secondary",
     "summary":"Kinematics: displacement, velocity, acceleration, equations of motion, relative velocity, free fall.",
     "topics":["kinematics","velocity","acceleration","equations of motion"]},
    {"board":"CBSE","class":11,"subject":"Physics","chapter_no":5,
     "chapter_title":"Laws of Motion","level":"secondary",
     "summary":"Newton's three laws, inertia, momentum, impulse, friction, circular motion dynamics.",
     "topics":["Newton's laws","inertia","friction","impulse"]},
    {"board":"CBSE","class":11,"subject":"Physics","chapter_no":6,
     "chapter_title":"Work, Energy and Power","level":"secondary",
     "summary":"Work-energy theorem, kinetic and potential energy, conservation of energy, power, collisions.",
     "topics":["work","energy","power","conservation","collision"]},
    {"board":"CBSE","class":11,"subject":"Physics","chapter_no":10,
     "chapter_title":"Mechanical Properties of Fluids","level":"secondary",
     "summary":"Pressure, Pascal's law, Archimedes' principle, viscosity, Bernoulli's equation, surface tension.",
     "topics":["pressure","Archimedes","Bernoulli","viscosity","surface tension"]},
    {"board":"CBSE","class":11,"subject":"Chemistry","chapter_no":1,
     "chapter_title":"Some Basic Concepts of Chemistry","level":"secondary",
     "summary":"Mole concept, Avogadro's number, molar mass, stoichiometry, empirical formula.",
     "topics":["mole","Avogadro","stoichiometry","molar mass"]},
    {"board":"CBSE","class":11,"subject":"Chemistry","chapter_no":2,
     "chapter_title":"Structure of Atom","level":"secondary",
     "summary":"Bohr model, quantum numbers, electronic configuration, wave-mechanical model, Aufbau principle.",
     "topics":["atom","quantum numbers","orbital","electronic configuration"]},
    {"board":"CBSE","class":11,"subject":"Chemistry","chapter_no":4,
     "chapter_title":"Chemical Bonding and Molecular Structure","level":"secondary",
     "summary":"Ionic, covalent, coordinate bonds; VSEPR theory; hybridisation; molecular orbital theory.",
     "topics":["ionic bond","covalent bond","VSEPR","hybridisation","MO theory"]},
    {"board":"CBSE","class":11,"subject":"Chemistry","chapter_no":6,
     "chapter_title":"Thermodynamics","level":"secondary",
     "summary":"System and surroundings, internal energy, enthalpy, Hess's law, entropy, Gibbs free energy.",
     "topics":["thermodynamics","enthalpy","entropy","Gibbs energy"]},
    {"board":"CBSE","class":11,"subject":"Chemistry","chapter_no":7,
     "chapter_title":"Equilibrium","level":"secondary",
     "summary":"Chemical equilibrium, Le Chatelier's principle, equilibrium constants Kp and Kc, ionic equilibrium, pH, buffer.",
     "topics":["equilibrium","Le Chatelier","Kp","Kc","pH","buffer"]},
    {"board":"CBSE","class":11,"subject":"Biology","chapter_no":5,
     "chapter_title":"Morphology of Flowering Plants","level":"secondary",
     "summary":"Root, stem, leaf, inflorescence, flower, fruit, seed morphology; families Fabaceae, Solanaceae, Liliaceae.",
     "topics":["morphology","root","stem","leaf","flower","fruit"]},
    {"board":"CBSE","class":11,"subject":"Biology","chapter_no":8,
     "chapter_title":"Cell: The Unit of Life","level":"secondary",
     "summary":"Prokaryotic and eukaryotic cell structure, cell organelles and their functions, cell membrane.",
     "topics":["cell","organelles","eukaryote","prokaryote","nucleus","mitochondria"]},
    {"board":"CBSE","class":11,"subject":"Biology","chapter_no":11,
     "chapter_title":"Transport in Plants","level":"secondary",
     "summary":"Diffusion, osmosis, water potential, xylem transport, phloem translocation.",
     "topics":["osmosis","diffusion","xylem","phloem","water potential"]},
    {"board":"CBSE","class":11,"subject":"Biology","chapter_no":14,
     "chapter_title":"Respiration in Plants","level":"secondary",
     "summary":"Glycolysis, Krebs cycle, electron transport chain, ATP synthesis, fermentation.",
     "topics":["glycolysis","Krebs cycle","ATP","fermentation","aerobic respiration"]},
    {"board":"CBSE","class":11,"subject":"Maths","chapter_no":1,
     "chapter_title":"Sets","level":"secondary",
     "summary":"Types of sets, Venn diagrams, union, intersection, complement, De Morgan's laws.",
     "topics":["sets","Venn diagram","union","intersection"]},
    {"board":"CBSE","class":11,"subject":"Maths","chapter_no":3,
     "chapter_title":"Trigonometric Functions","level":"secondary",
     "summary":"Radian measure, trigonometric functions, identities, general solutions of trig equations.",
     "topics":["trigonometry","radian","identities","equations"]},
    {"board":"CBSE","class":11,"subject":"Maths","chapter_no":8,
     "chapter_title":"Binomial Theorem","level":"secondary",
     "summary":"Binomial theorem for positive integral index, general and middle terms, Pascal's triangle.",
     "topics":["binomial theorem","Pascal's triangle","combinations"]},
    {"board":"CBSE","class":11,"subject":"Maths","chapter_no":13,
     "chapter_title":"Statistics","level":"secondary",
     "summary":"Mean deviation, variance, standard deviation for ungrouped and grouped data.",
     "topics":["statistics","mean deviation","variance","standard deviation"]},

    # ===================== CBSE Class 12 =====================
    {"board":"CBSE","class":12,"subject":"Physics","chapter_no":1,
     "chapter_title":"Electric Charges and Fields","level":"secondary",
     "summary":"Coulomb's law, electric field, field lines, Gauss's law, dipole.",
     "topics":["electric charge","Coulomb's law","electric field","Gauss's law"]},
    {"board":"CBSE","class":12,"subject":"Physics","chapter_no":2,
     "chapter_title":"Electrostatic Potential and Capacitance","level":"secondary",
     "summary":"Potential, potential energy, equipotential surfaces, conductors, capacitors, dielectrics.",
     "topics":["potential","capacitor","dielectric","equipotential"]},
    {"board":"CBSE","class":12,"subject":"Physics","chapter_no":4,
     "chapter_title":"Moving Charges and Magnetism","level":"secondary",
     "summary":"Lorentz force, cyclotron, Biot-Savart law, Ampere's law, solenoid, torque on current loop.",
     "topics":["Lorentz force","Biot-Savart","Ampere's law","solenoid"]},
    {"board":"CBSE","class":12,"subject":"Physics","chapter_no":7,
     "chapter_title":"Alternating Current","level":"secondary",
     "summary":"AC generator, rms values, phasors, LC and LCR circuits, resonance, transformers.",
     "topics":["AC","rms","resonance","LCR circuit","transformer"]},
    {"board":"CBSE","class":12,"subject":"Physics","chapter_no":9,
     "chapter_title":"Ray Optics and Optical Instruments","level":"secondary",
     "summary":"Reflection, refraction, prism, total internal reflection, lenses, microscope, telescope.",
     "topics":["ray optics","refraction","prism","lens","telescope"]},
    {"board":"CBSE","class":12,"subject":"Physics","chapter_no":12,
     "chapter_title":"Atoms","level":"secondary",
     "summary":"Bohr model, energy levels, hydrogen spectrum, de Broglie hypothesis.",
     "topics":["Bohr model","hydrogen spectrum","de Broglie"]},
    {"board":"CBSE","class":12,"subject":"Physics","chapter_no":13,
     "chapter_title":"Nuclei","level":"secondary",
     "summary":"Nuclear size, mass-energy equivalence, binding energy, radioactivity, nuclear reactions.",
     "topics":["nucleus","binding energy","radioactivity","fission","fusion"]},
    {"board":"CBSE","class":12,"subject":"Chemistry","chapter_no":1,
     "chapter_title":"The Solid State","level":"secondary",
     "summary":"Crystal systems, unit cell, packing efficiency, defects in crystals, semiconductors.",
     "topics":["solid state","unit cell","crystal","packing efficiency","defects"]},
    {"board":"CBSE","class":12,"subject":"Chemistry","chapter_no":3,
     "chapter_title":"Electrochemistry","level":"secondary",
     "summary":"Electrochemical cells, EMF, Nernst equation, conductance, electrolysis, corrosion.",
     "topics":["electrochemistry","EMF","Nernst equation","electrolysis","corrosion"]},
    {"board":"CBSE","class":12,"subject":"Chemistry","chapter_no":4,
     "chapter_title":"Chemical Kinetics","level":"secondary",
     "summary":"Rate of reaction, order, molecularity, integrated rate laws, Arrhenius equation, activation energy.",
     "topics":["kinetics","rate law","order","Arrhenius","activation energy"]},
    {"board":"CBSE","class":12,"subject":"Chemistry","chapter_no":10,
     "chapter_title":"Haloalkanes and Haloarenes","level":"secondary",
     "summary":"Nomenclature, properties, substitution and elimination reactions, SN1, SN2, stereochemistry.",
     "topics":["haloalkanes","SN1","SN2","elimination","stereochemistry"]},
    {"board":"CBSE","class":12,"subject":"Biology","chapter_no":1,
     "chapter_title":"Reproduction in Organisms","level":"secondary",
     "summary":"Asexual and sexual reproduction, vegetative propagation, life span of organisms.",
     "topics":["reproduction","asexual","sexual","vegetative propagation"]},
    {"board":"CBSE","class":12,"subject":"Biology","chapter_no":2,
     "chapter_title":"Sexual Reproduction in Flowering Plants","level":"secondary",
     "summary":"Flower structure, pollination, fertilisation, seed formation, double fertilisation.",
     "topics":["pollination","fertilisation","double fertilisation","seed","fruit"]},
    {"board":"CBSE","class":12,"subject":"Biology","chapter_no":5,
     "chapter_title":"Principles of Inheritance and Variation","level":"secondary",
     "summary":"Mendel's laws, monohybrid and dihybrid cross, dominance, linkage, chromosomal theory.",
     "topics":["Mendel","genetics","dominance","inheritance","chromosomes"]},
    {"board":"CBSE","class":12,"subject":"Biology","chapter_no":6,
     "chapter_title":"Molecular Basis of Inheritance","level":"secondary",
     "summary":"DNA structure, replication, transcription, translation, genetic code, regulation.",
     "topics":["DNA","replication","transcription","translation","genetic code"]},
    {"board":"CBSE","class":12,"subject":"Maths","chapter_no":1,
     "chapter_title":"Relations and Functions","level":"secondary",
     "summary":"Types of relations, functions, composition, invertible functions, binary operations.",
     "topics":["relations","functions","composition","inverse"]},
    {"board":"CBSE","class":12,"subject":"Maths","chapter_no":5,
     "chapter_title":"Continuity and Differentiability","level":"secondary",
     "summary":"Continuity, differentiability, chain rule, implicit differentiation, logarithmic differentiation, Rolle's theorem.",
     "topics":["continuity","differentiability","chain rule","Rolle's theorem"]},
    {"board":"CBSE","class":12,"subject":"Maths","chapter_no":8,
     "chapter_title":"Application of Integrals","level":"secondary",
     "summary":"Area under curves, area between curves, definite integration as area.",
     "topics":["integration","area","definite integral"]},

    # ===================== ICSE / ISC Class 9-10 =====================
    {"board":"ICSE","class":9,"subject":"Physics","chapter_no":1,
     "chapter_title":"Measurements and Experimentation","level":"secondary",
     "summary":"SI units, measurement of length, mass, time; simple pendulum, vernier callipers, screw gauge.",
     "topics":["measurement","SI units","vernier","pendulum"]},
    {"board":"ICSE","class":9,"subject":"Physics","chapter_no":2,
     "chapter_title":"Motion in One Dimension","level":"secondary",
     "summary":"Scalar and vector quantities, displacement, velocity, acceleration, equations of motion.",
     "topics":["motion","kinematics","scalar","vector","equations of motion"]},
    {"board":"ICSE","class":9,"subject":"Physics","chapter_no":3,
     "chapter_title":"Laws of Motion","level":"secondary",
     "summary":"Newton's three laws, inertia, momentum, impulse, friction.",
     "topics":["Newton's laws","inertia","friction","momentum"]},
    {"board":"ICSE","class":9,"subject":"Chemistry","chapter_no":1,
     "chapter_title":"The Language of Chemistry","level":"secondary",
     "summary":"Chemical symbols, formulae, equations, types of reactions, balancing equations.",
     "topics":["chemical formula","equation","balancing","nomenclature"]},
    {"board":"ICSE","class":9,"subject":"Chemistry","chapter_no":2,
     "chapter_title":"Chemical Changes and Reactions","level":"secondary",
     "summary":"Exothermic and endothermic reactions, types of chemical changes, oxidation-reduction.",
     "topics":["chemical reaction","exothermic","endothermic","redox"]},
    {"board":"ICSE","class":9,"subject":"Biology","chapter_no":1,
     "chapter_title":"Basic Biology: Cell","level":"secondary",
     "summary":"Cell theory, plant and animal cells, cell organelles, differences between plant and animal cells.",
     "topics":["cell","organelles","plant cell","animal cell"]},
    {"board":"ICSE","class":10,"subject":"Physics","chapter_no":1,
     "chapter_title":"Force","level":"secondary",
     "summary":"Turning effect of force, moments, centre of gravity, uniform circular motion, centripetal force.",
     "topics":["force","moment","centre of gravity","centripetal force"]},
    {"board":"ICSE","class":10,"subject":"Physics","chapter_no":5,
     "chapter_title":"Refraction of Light","level":"secondary",
     "summary":"Laws of refraction, refractive index, real and apparent depth, total internal reflection, lenses.",
     "topics":["refraction","refractive index","TIR","lens","critical angle"]},
    {"board":"ICSE","class":10,"subject":"Chemistry","chapter_no":7,
     "chapter_title":"Metallurgy","level":"secondary",
     "summary":"Occurrence, extraction and refining of metals; alloys; corrosion.",
     "topics":["metallurgy","extraction","alloy","corrosion"]},
    {"board":"ICSE","class":10,"subject":"Biology","chapter_no":3,
     "chapter_title":"Genetics","level":"secondary",
     "summary":"Mendel's laws, monohybrid/dihybrid crosses, sex determination, mutation.",
     "topics":["genetics","Mendel","chromosome","mutation","sex determination"]},

    # ===================== Maharashtra State Board (SSC/HSC) =====================
    {"board":"Maharashtra","class":9,"subject":"Science","chapter_no":1,
     "chapter_title":"Laws of Motion","level":"secondary",
     "summary":"Newton's laws, inertia, momentum, law of conservation of momentum.",
     "topics":["Newton's laws","momentum","inertia"]},
    {"board":"Maharashtra","class":9,"subject":"Science","chapter_no":7,
     "chapter_title":"Motion, Force and Work","level":"secondary",
     "summary":"Uniform and non-uniform motion, friction, pressure, buoyancy, work and energy.",
     "topics":["motion","friction","pressure","work","energy"]},
    {"board":"Maharashtra","class":10,"subject":"Science Part I","chapter_no":1,
     "chapter_title":"Gravitation","level":"secondary",
     "summary":"Universal law of gravitation, free fall, escape velocity, satellite motion.",
     "topics":["gravitation","free fall","escape velocity","satellite"]},
    {"board":"Maharashtra","class":10,"subject":"Science Part II","chapter_no":2,
     "chapter_title":"Life Processes in Living Organisms","level":"secondary",
     "summary":"Nutrition, respiration, transportation, excretion in plants and animals.",
     "topics":["nutrition","respiration","excretion","transportation"]},
    {"board":"Maharashtra","class":11,"subject":"Physics","chapter_no":2,
     "chapter_title":"Mathematical Methods","level":"secondary",
     "summary":"Vectors, scalars, dot and cross product, differentiation and integration basics for physics.",
     "topics":["vectors","dot product","cross product","calculus"]},
    {"board":"Maharashtra","class":12,"subject":"Physics","chapter_no":1,
     "chapter_title":"Rotational Dynamics","level":"secondary",
     "summary":"Moment of inertia, angular momentum, torque, rolling motion, conservation of angular momentum.",
     "topics":["rotational motion","moment of inertia","angular momentum","torque"]},

    # ===================== Tamil Nadu State Board (Samacheer Kalvi) =====================
    {"board":"TamilNadu","class":9,"subject":"Science","chapter_no":1,
     "chapter_title":"Measurement","level":"secondary",
     "summary":"Physical quantities, SI units, measurement of length, area, volume, mass, time.",
     "topics":["measurement","SI units","length","volume","mass"]},
    {"board":"TamilNadu","class":10,"subject":"Science","chapter_no":1,
     "chapter_title":"Laws of Motion","level":"secondary",
     "summary":"Newton's laws, projectile motion, applications in sports and technology.",
     "topics":["Newton's laws","projectile","motion","applications"]},
    {"board":"TamilNadu","class":11,"subject":"Physics","chapter_no":4,
     "chapter_title":"Work, Energy and Power","level":"secondary",
     "summary":"Work-energy theorem, conservative and non-conservative forces, potential energy, collisions.",
     "topics":["work","energy","power","collisions","conservative forces"]},
    {"board":"TamilNadu","class":12,"subject":"Chemistry","chapter_no":3,
     "chapter_title":"p-Block Elements I","level":"secondary",
     "summary":"Properties and compounds of Group 13 and 14 elements: aluminium, carbon, silicon.",
     "topics":["p-block","boron","carbon","silicon","aluminium"]},

    # ===================== Karnataka State Board =====================
    {"board":"Karnataka","class":9,"subject":"Science","chapter_no":8,
     "chapter_title":"Motion","level":"secondary",
     "summary":"Distance and displacement, speed and velocity, acceleration, equations of motion.",
     "topics":["motion","velocity","acceleration","equations of motion"]},
    {"board":"Karnataka","class":10,"subject":"Science","chapter_no":12,
     "chapter_title":"Electricity","level":"secondary",
     "summary":"Electric current, Ohm's law, resistance, Joule heating, electric power.",
     "topics":["electricity","Ohm's law","resistance","Joule heating"]},

    # ===================== AP / Telangana State Board =====================
    {"board":"AP_Telangana","class":9,"subject":"Physical Science","chapter_no":1,
     "chapter_title":"Matter Around Us","level":"secondary",
     "summary":"States of matter, properties, physical and chemical changes.",
     "topics":["matter","states","physical change","chemical change"]},
    {"board":"AP_Telangana","class":10,"subject":"Physical Science","chapter_no":11,
     "chapter_title":"Electromagnetism","level":"secondary",
     "summary":"Magnetic effect of electric current, electromagnetic induction, AC generator, transformer.",
     "topics":["electromagnetism","induction","generator","transformer"]},
    {"board":"AP_Telangana","class":10,"subject":"Biology","chapter_no":2,
     "chapter_title":"Nutrition","level":"secondary",
     "summary":"Modes of nutrition, photosynthesis, human digestive system.",
     "topics":["nutrition","photosynthesis","digestion","autotroph","heterotroph"]},

    # ===================== UP Board =====================
    {"board":"UP","class":9,"subject":"Science","chapter_no":8,
     "chapter_title":"Motion","level":"secondary",
     "summary":"Uniform and non-uniform motion, speed, velocity, acceleration, equations of motion.",
     "topics":["motion","velocity","acceleration","equations of motion"]},
    {"board":"UP","class":10,"subject":"Science","chapter_no":1,
     "chapter_title":"Chemical Reactions and Equations","level":"secondary",
     "summary":"Types of chemical reactions, balancing chemical equations.",
     "topics":["chemical reaction","balancing","redox","decomposition"]},

    # ===================== NEET Topics (Competitive Exam) =====================
    {"board":"NEET","class":12,"subject":"Biology","chapter_no":1,
     "chapter_title":"Reproduction in Organisms (NEET)","level":"neet_jee",
     "summary":"NEET-focused: asexual and sexual reproduction, vegetative propagation, key definitions and differences.",
     "topics":["reproduction","NEET","asexual","sexual","vegetative propagation"]},
    {"board":"NEET","class":12,"subject":"Biology","chapter_no":2,
     "chapter_title":"Sexual Reproduction in Flowering Plants (NEET)","level":"neet_jee",
     "summary":"NEET-focused: pollination types, male and female gametophyte, fertilisation, apomixis, polyembryony.",
     "topics":["pollination","fertilisation","gametophyte","apomixis","NEET"]},
    {"board":"NEET","class":12,"subject":"Biology","chapter_no":5,
     "chapter_title":"Principles of Inheritance (NEET)","level":"neet_jee",
     "summary":"NEET-focused: Mendel's laws, monohybrid ratio, dihybrid ratio, codominance, incomplete dominance.",
     "topics":["genetics","Mendel","NEET","inheritance","dominance"]},
    {"board":"NEET","class":12,"subject":"Biology","chapter_no":16,
     "chapter_title":"Environmental Issues (NEET)","level":"neet_jee",
     "summary":"NEET-focused: air/water/soil pollution, biomagnification, ozone depletion, greenhouse effect.",
     "topics":["pollution","NEET","environment","ozone","greenhouse effect"]},
    {"board":"NEET","class":11,"subject":"Physics","chapter_no":2,
     "chapter_title":"Units and Dimensions (NEET)","level":"neet_jee",
     "summary":"NEET Physics: SI units, dimensional analysis, significant figures — high-yield quick-revision.",
     "topics":["units","dimensions","NEET","Physics","SI units"]},
    {"board":"NEET","class":11,"subject":"Chemistry","chapter_no":1,
     "chapter_title":"Mole Concept (NEET)","level":"neet_jee",
     "summary":"NEET Chemistry: mole concept, Avogadro's law, molar mass, stoichiometry — high-yield chapter.",
     "topics":["mole","Avogadro","stoichiometry","NEET","Chemistry"]},

    # ===================== JEE Topics (Competitive Exam) =====================
    {"board":"JEE","class":11,"subject":"Physics","chapter_no":1,
     "chapter_title":"Kinematics (JEE)","level":"neet_jee",
     "summary":"JEE-focused: relative motion, projectile, circular motion — derivation-level treatment.",
     "topics":["kinematics","projectile","circular motion","JEE","derivation"]},
    {"board":"JEE","class":11,"subject":"Physics","chapter_no":5,
     "chapter_title":"Rotational Mechanics (JEE)","level":"neet_jee",
     "summary":"JEE Advanced favourite: moment of inertia derivations, rolling, angular momentum conservation.",
     "topics":["rotational mechanics","JEE","moment of inertia","angular momentum","rolling"]},
    {"board":"JEE","class":11,"subject":"Chemistry","chapter_no":1,
     "chapter_title":"Atomic Structure (JEE)","level":"neet_jee",
     "summary":"JEE-focused: Bohr model, quantum numbers, orbital shapes, aufbau, Hund's rule, photoelectric effect.",
     "topics":["atomic structure","JEE","Bohr","quantum numbers","orbital"]},
    {"board":"JEE","class":12,"subject":"Maths","chapter_no":1,
     "chapter_title":"Matrices and Determinants (JEE)","level":"neet_jee",
     "summary":"JEE-focused: matrix operations, determinants, Cramer's rule, eigenvalues — full JEE pattern treatment.",
     "topics":["matrices","determinants","JEE","Cramer's rule","eigenvalues"]},
    {"board":"JEE","class":12,"subject":"Maths","chapter_no":2,
     "chapter_title":"Calculus: Limits, Derivatives, Integrals (JEE)","level":"neet_jee",
     "summary":"JEE-focused: limits, L'Hôpital's rule, definite integrals, area, differential equations.",
     "topics":["calculus","limits","derivatives","integrals","JEE"]},
    {"board":"JEE","class":12,"subject":"Physics","chapter_no":1,
     "chapter_title":"Electrostatics (JEE)","level":"neet_jee",
     "summary":"JEE Advanced: Gauss's law applications, potential due to continuous charge distributions, conductors.",
     "topics":["electrostatics","JEE","Gauss's law","potential","capacitor"]},
]


SUBJECTS = sorted({t["subject"] for t in CURRICULUM})
BOARDS = sorted({t["board"] for t in CURRICULUM})
CLASSES = sorted({t["class"] for t in CURRICULUM})
