"""Starter flashcard decks — written to actual syllabus of each board / exam.

Used by `POST /api/flashcards/seed-starter` to create real entries in the
user's SRS database the first time they visit `/flashcards`. After
seeding, the cards behave exactly like ones they imported or generated
themselves: they go through the SM-2 scheduler, get rated, build up
real review history.

Same content as the dashboard's `DECKS` catalog (kept in sync manually
for now — see `padhai/web.py` `var DECKS = ...`). Move both to a shared
JSON file later if drift becomes a problem.
"""
from __future__ import annotations

from typing import Any

# Each deck: title, description, language, list of (front, back, hint?) cards.
# Title kept under 200 chars (SRS validates that).
STARTER_DECKS: list[dict[str, Any]] = [
    {
        "key": "cbse_6_8",
        "title": "CBSE Class 6–8 — Starter deck",
        "description": "Core concepts across Math, Science, History, Geography, GK and Civics for CBSE Class 6 to 8.",
        "language": "en",
        "topic_code": "cbse_middle_school",
        "cards": [
            ("Define a fraction.",
             "A number representing a part of a whole, written as a/b where a is the numerator and b is the denominator (b ≠ 0)."),
            ("Area of a rectangle with length l and breadth b?",
             "Area = l × b. SI unit: square metre (m²)."),
            ("What is the HCF of 12 and 18?",
             "6 — the common factors of 12 and 18 are 1, 2, 3, 6; the highest is 6."),
            ("What is photosynthesis?",
             "The process where green plants use sunlight, CO₂ and water to make food (glucose), releasing oxygen."),
            ("Name the three states of matter.",
             "Solid, Liquid, Gas. (Plasma is the fourth state, found in stars and lightning.)"),
            ("Which is the largest planet in our solar system?",
             "Jupiter — about 11 times the diameter of Earth and over 300 times Earth's mass."),
            ("Who founded the Mauryan Empire?",
             "Chandragupta Maurya, around 322 BCE, after defeating the Nanda dynasty."),
            ("What is the longest river in India?",
             "The Ganga — approximately 2,525 km from Gangotri to the Bay of Bengal."),
            ("What is the capital of India?",
             "New Delhi."),
            ("Name the three branches of the Indian government.",
             "Legislature (makes laws — Parliament), Executive (enforces laws — PM and Council of Ministers), Judiciary (interprets laws — Supreme Court)."),
        ],
    },
    {
        "key": "cbse_9_10",
        "title": "CBSE Class 9–10 (Board) — Starter deck",
        "description": "Board-exam essentials: Physics, Chemistry, Math, Biology, Economics and History.",
        "language": "en",
        "topic_code": "cbse_secondary",
        "cards": [
            ("State Newton's Second Law of Motion.",
             "F = m × a — the net force on an object equals its mass times its acceleration. SI unit of force: Newton (N)."),
            ("What is Ohm's Law?",
             "V = I × R — voltage across a conductor is directly proportional to the current through it, at constant temperature."),
            ("Difference between atomic number and mass number?",
             "Atomic number (Z) = number of protons in the nucleus. Mass number (A) = protons + neutrons."),
            ("Define an acid in chemistry.",
             "A substance that releases H⁺ ions in aqueous solution; turns blue litmus red; pH < 7. Examples: HCl, H₂SO₄, HNO₃."),
            ("State the Pythagoras Theorem.",
             "In a right-angled triangle: a² + b² = c², where c is the hypotenuse and a, b are the other two sides."),
            ("Write the quadratic formula.",
             "x = (−b ± √(b² − 4ac)) / (2a), for ax² + bx + c = 0 (a ≠ 0)."),
            ("Write the photosynthesis equation.",
             "6CO₂ + 6H₂O → (sunlight + chlorophyll) → C₆H₁₂O₆ + 6O₂."),
            ("Name the three sectors of the Indian economy.",
             "Primary (agriculture, fishing, mining), Secondary (manufacturing), Tertiary (services)."),
            ("Who led the Salt March / Dandi March in 1930?",
             "Mahatma Gandhi — a 240-mile march from Sabarmati Ashram to Dandi protesting the British salt tax."),
            ("What is the SI unit of electrical resistance?",
             "Ohm (Ω) — defined as 1 volt per ampere (1 V/A)."),
            ("What is the difference between mitosis and meiosis?",
             "Mitosis: 2 identical diploid daughter cells, used for growth and tissue repair. Meiosis: 4 genetically distinct haploid cells (gametes)."),
        ],
    },
    {
        "key": "cbse_11_12",
        "title": "CBSE Class 11–12 (Board) — Starter deck",
        "description": "Class 11 and 12 board level Physics, Chemistry, Math and Biology.",
        "language": "en",
        "topic_code": "cbse_higher_secondary",
        "cards": [
            ("Define work in physics.",
             "W = F · d · cos θ — the dot product of force and displacement. SI unit: Joule (J)."),
            ("State Le Chatelier's Principle.",
             "If a system at equilibrium is disturbed by a change in concentration, temperature or pressure, the system shifts to oppose the change and restore equilibrium."),
            ("What is the derivative of sin(x)?",
             "cos(x). Related: d/dx[cos x] = −sin x; d/dx[tan x] = sec² x."),
            ("Write the integration-by-parts formula.",
             "∫u dv = u·v − ∫v du. Pick u by LIATE: Log, Inverse-trig, Algebraic, Trig, Exponential."),
            ("What is mitosis?",
             "Cell division that produces two genetically identical diploid daughter cells. Stages: Prophase, Metaphase, Anaphase, Telophase (PMAT)."),
            ("State Mendel's Law of Segregation.",
             "During gamete formation, the two alleles for each heritable trait separate, so each gamete carries only one allele for that trait."),
            ("State the right-hand rule for a current-carrying wire.",
             "Thumb points along the current direction; curled fingers point in the direction of the magnetic field circling the wire."),
            ("What is the hybridization of carbon in methane (CH₄)?",
             "sp³ — tetrahedral geometry, 4 equivalent C–H bonds at 109.5°."),
            ("State the value of Avogadro's number.",
             "6.022 × 10²³ particles per mole."),
            ("Write the kinematic equation that links v, u, a, s.",
             "v² = u² + 2as. Here u = initial velocity, v = final velocity, a = acceleration, s = displacement."),
            ("State the van't Hoff equation for osmotic pressure.",
             "π = M·R·T, where M = molarity, R = gas constant, T = absolute temperature (Kelvin)."),
        ],
    },
    {
        "key": "jee",
        "title": "JEE Main + Advanced — Starter deck",
        "description": "Physics, Chemistry and Mathematics essentials for JEE Main and JEE Advanced.",
        "language": "en",
        "topic_code": "jee",
        "cards": [
            ("Equation of an ellipse centred at origin (a > b)?",
             "x²/a² + y²/b² = 1. Eccentricity e = √(1 − b²/a²); foci at (±ae, 0); directrix x = ±a/e."),
            ("State the Lorentz force on a charged particle.",
             "F = q(E + v × B). The magnetic component (qv × B) does no work — only changes direction."),
            ("Write Einstein's photoelectric equation.",
             "K_max = hν − φ. φ = work function of the metal; threshold frequency ν₀ = φ/h."),
            ("What is nCr (binomial coefficient)?",
             "nCr = n! / (r! · (n−r)!) — the number of ways to choose r objects from n distinct objects."),
            ("Give the IUPAC name of (CH₃)₂CH–CH₂–OH.",
             "2-methylpropan-1-ol (common name: isobutanol)."),
            ("Doppler effect — observer moving toward a stationary source?",
             "f' = f × (v + v₀) / v, where v₀ = observer's speed, v = speed of sound in the medium."),
            ("Name the strongest field ligand in the spectrochemical series.",
             "CO (carbonyl) — produces the largest crystal-field splitting Δ. Series (low to high Δ): I⁻ < Br⁻ < Cl⁻ < F⁻ < OH⁻ < H₂O < NH₃ < CN⁻ < CO."),
            ("Evaluate lim x→0 of (sin x)/x.",
             "1. Standard limit; used to derive d/dx(sin x) = cos x."),
            ("State the Bohr radius of the hydrogen atom.",
             "a₀ = 0.529 Å = 5.29 × 10⁻¹¹ m — the radius of the n=1 orbit."),
            ("Write the de Broglie wavelength formula.",
             "λ = h / p = h / (m·v). All matter has wave properties; significant only at quantum scales."),
            ("Sum of an infinite geometric progression (|r| < 1)?",
             "S∞ = a / (1 − r). Valid only when |r| < 1; otherwise the series diverges."),
        ],
    },
    {
        "key": "neet",
        "title": "NEET UG — Starter deck",
        "description": "Biology-heavy NEET UG essentials, plus core Chemistry and Physics topics.",
        "language": "en",
        "topic_code": "neet",
        "cards": [
            ("Where in the chloroplast does the Calvin cycle (dark reaction) occur?",
             "Stroma — the fluid surrounding the thylakoids. It uses ATP + NADPH from the light reaction to fix CO₂ into G3P."),
            ("Why are mitochondria called the 'powerhouse of the cell'?",
             "They produce most of the cell's ATP through the Krebs cycle and oxidative phosphorylation on the inner mitochondrial membrane."),
            ("Largest gland in the human body?",
             "Liver (~1.5 kg in adults). Produces bile, detoxifies blood, stores glycogen, and synthesises plasma proteins."),
            ("Which pancreatic cells secrete insulin?",
             "β (beta) cells in the Islets of Langerhans. α cells secrete glucagon; δ cells secrete somatostatin."),
            ("State Mendel's Law of Independent Assortment.",
             "Genes for different traits assort independently during gamete formation — strictly true only for unlinked genes on different chromosomes."),
            ("How many pairs of cranial nerves are there in humans?",
             "12 pairs: Olfactory, Optic, Oculomotor, Trochlear, Trigeminal, Abducens, Facial, Vestibulocochlear, Glossopharyngeal, Vagus, Accessory, Hypoglossal."),
            ("IUPAC name of acetone (CH₃COCH₃)?",
             "Propan-2-one."),
            ("State Markovnikov's rule.",
             "In addition of HX to an unsymmetrical alkene, H attaches to the carbon already bearing more H atoms; X goes to the more substituted carbon."),
            ("Bohr's angular-momentum quantization condition?",
             "L = m·v·r = n·h / (2π), where n = 1, 2, 3, … (the principal quantum number)."),
            ("Primary function of ribosomes?",
             "Site of protein synthesis — they translate mRNA into polypeptide chains. Found free in cytoplasm or attached to rough ER."),
            ("Who is the universal blood donor and why?",
             "O-negative — has no A, B or Rh antigens on RBC surface, so the recipient's immune system does not reject it."),
        ],
    },
    {
        "key": "upsc",
        "title": "UPSC Civil Services — Starter deck",
        "description": "Polity, History, Geography and Economy fundamentals for UPSC CSE Prelims and Mains.",
        "language": "en",
        "topic_code": "upsc",
        "cards": [
            ("State Article 14 of the Indian Constitution.",
             "Right to Equality before law — 'The State shall not deny to any person equality before the law or the equal protection of the laws within the territory of India.'"),
            ("Article 32 vs Article 226?",
             "Article 32: Supreme Court's writ jurisdiction — only for Fundamental Rights, considered a Fundamental Right itself. Article 226: High Court's writ jurisdiction — broader, can be used for any legal right."),
            ("Who appoints the Comptroller and Auditor General (CAG) of India?",
             "The President of India (Article 148). Tenure: 6 years or 65 years of age, whichever is earlier. Removed only by the same process as a Supreme Court judge."),
            ("What are the Directive Principles of State Policy (DPSP)?",
             "Part IV (Articles 36–51) — non-justiciable guidelines borrowed from the Irish Constitution. Examples: equal pay for equal work, free legal aid, Uniform Civil Code, environmental protection."),
            ("Who founded the Indian National Congress in 1885?",
             "Allan Octavian Hume (retired British civil servant). First session: Bombay, December 1885; first president: W. C. Bonnerjee."),
            ("Which Mauryan emperor adopted Buddhism after a war?",
             "Ashoka the Great, after the Kalinga War (~261 BCE). He spread Buddhism through rock and pillar edicts and sent missions abroad (including his son Mahinda to Sri Lanka)."),
            ("Source and mouth of the Ganga river?",
             "Source: Gangotri Glacier in Uttarakhand. Mouth: Bay of Bengal via the Sundarbans delta (West Bengal and Bangladesh)."),
            ("What is the Cash Reserve Ratio (CRR)?",
             "The percentage of total deposits a commercial bank must keep with the RBI as reserves. The RBI uses CRR as a monetary-policy tool to control liquidity in the banking system."),
            ("Sangam literature is associated with which dynasties?",
             "The Cholas, Pandyas and Cheras — early-historical Tamil dynasties (~300 BCE to 300 CE) of South India."),
            ("What is a Western Disturbance?",
             "An extra-tropical storm originating in the Mediterranean / Caspian Sea region that brings winter rainfall to North-West India and snowfall to the Himalayas. It is critical for rabi crops."),
            ("Key changes brought by the 42nd Constitutional Amendment (1976)?",
             "Called the 'Mini-Constitution'. Added 'Socialist' and 'Secular' to the Preamble, made DPSPs override Fundamental Rights, and added 10 Fundamental Duties (Article 51A)."),
        ],
    },
    {
        "key": "icse",
        "title": "ICSE / ISC (CISCE) — Starter deck",
        "description": "Council for the Indian School Certificate Examinations (Class 10 and 12) essentials.",
        "language": "en",
        "topic_code": "icse",
        "cards": [
            ("Total surface area of a cone (radius r, slant height l)?",
             "TSA = π·r² + π·r·l = π·r·(r + l). Curved surface area (CSA) = π·r·l."),
            ("Define photosynthesis (ICSE Biology).",
             "The process by which green plants synthesise organic food (glucose) from CO₂ and water, using sunlight as energy and chlorophyll as catalyst, releasing O₂ as a by-product."),
            ("State Boyle's Law.",
             "At constant temperature, the pressure of a fixed mass of gas is inversely proportional to its volume: P·V = constant, so P₁V₁ = P₂V₂."),
            ("State Charles's Law.",
             "At constant pressure, the volume of a fixed mass of gas is directly proportional to its absolute temperature (Kelvin): V/T = constant, so V₁/T₁ = V₂/T₂."),
            ("Define molarity.",
             "Number of moles of solute per litre of solution: M = (moles of solute) / (volume of solution in L)."),
            ("Formula for the slope of a line through (x₁, y₁) and (x₂, y₂)?",
             "m = (y₂ − y₁) / (x₂ − x₁). If x₁ = x₂ (vertical line), slope is undefined."),
            ("Define osmosis.",
             "Net movement of solvent molecules (usually water) across a selectively permeable membrane from a region of lower solute concentration to one of higher solute concentration."),
            ("Who founded the Maratha Empire?",
             "Chhatrapati Shivaji Maharaj — crowned at Raigad Fort in 1674. He used guerrilla warfare (Ganimi Kava) against the Mughals and Bijapur Sultanate."),
            ("State Faraday's law of electromagnetic induction.",
             "EMF = −dΦ/dt — the induced EMF in a closed circuit equals the negative rate of change of magnetic flux. The negative sign expresses Lenz's law (it opposes the change)."),
            ("SI unit of work / energy?",
             "Joule (J). 1 J = 1 N·m = 1 kg·m²/s²."),
            ("Which chromosomal disorder is caused by trisomy 21?",
             "Down's syndrome — an extra copy of chromosome 21, giving 47 chromosomes instead of 46."),
        ],
    },
    {
        "key": "state",
        "title": "State boards (MH / TN / KA / AP / UP) — Starter deck",
        "description": "Geography, History, Polity and GK relevant to major Indian state boards.",
        "language": "en",
        "topic_code": "state_boards",
        "cards": [
            ("When was Maharashtra State formed, and from which parent state?",
             "1 May 1960 — Bombay State was split into Maharashtra (Marathi-speaking) and Gujarat (Gujarati-speaking)."),
            ("Capital of Karnataka?",
             "Bengaluru (formally renamed from Bangalore in 2014)."),
            ("Formation date and parent state of Telangana?",
             "2 June 2014 — carved out of Andhra Pradesh as India's 29th state. Capital: Hyderabad."),
            ("Largest river delta in India?",
             "The Sundarbans Delta — formed by the Ganga and Brahmaputra. It spans West Bengal (India) and Bangladesh and is a UNESCO World Heritage Site."),
            ("Official language and capital of Tamil Nadu?",
             "Tamil (one of the world's oldest classical languages). Capital: Chennai (formerly Madras)."),
            ("In which state is the Konark Sun Temple, and who built it?",
             "Odisha — built around 1250 CE by King Narasimhadeva I of the Eastern Ganga dynasty. UNESCO World Heritage Site."),
            ("Highest peak in the Western Ghats?",
             "Anamudi (~2,695 m) in Kerala — also the highest peak in South India outside the Himalayas."),
            ("Asia's largest tulip garden is in which Indian state?",
             "Jammu & Kashmir — the Indira Gandhi Memorial Tulip Garden in Srinagar, on the Zabarwan foothills near Dal Lake."),
            ("Capital of Bihar and its ancient name?",
             "Patna — ancient Pataliputra, capital of the Mauryan and Gupta empires."),
            ("Which state is known as the 'Spice Garden of India'?",
             "Kerala — major producer of cardamom, black pepper, ginger, cinnamon, cloves and nutmeg."),
            ("Which body conducts UP Board examinations?",
             "UPMSP — Uttar Pradesh Madhyamik Shiksha Parishad, headquartered in Prayagraj."),
        ],
    },
    {
        "key": "bank_ssc",
        "title": "Bank / SSC / Government exams — Starter deck",
        "description": "Quantitative aptitude, reasoning, banking awareness and current GK for IBPS, SBI, SSC and railway exams.",
        "language": "en",
        "topic_code": "bank_ssc",
        "cards": [
            ("Profit and Loss percentages are always calculated over what?",
             "Always over Cost Price (CP). Profit% = (Profit / CP) × 100; Loss% = (Loss / CP) × 100."),
            ("Write the Simple Interest formula.",
             "SI = (P × R × T) / 100, where P = principal, R = rate of interest per annum, T = time in years. Amount = P + SI."),
            ("Write the Compound Interest formula (annual compounding).",
             "A = P × (1 + R/100)ⁿ, for n full years compounded annually. CI = A − P."),
            ("Average of the first n natural numbers?",
             "(n + 1) / 2. Example: average of 1 to 10 = 5.5."),
            ("How many squares (of all sizes) are there on a standard chessboard?",
             "204 — sum of 1² + 2² + … + 8² = 8 · 9 · 17 / 6 = 204."),
            ("Relationship between speed, distance and time? And the average-speed formula for equal distances at two speeds a and b?",
             "Speed = Distance / Time. Average speed for equal distances at speeds a and b = 2ab / (a + b) (harmonic mean)."),
            ("Who appoints the Governor of the Reserve Bank of India (RBI)?",
             "The Central Government, on recommendation by the Financial Sector Regulatory Appointments Search Committee (FSRASC)."),
            ("Largest desert in the world by area?",
             "The Antarctic Polar Desert (cold desert, ~14 million km²). The Sahara is the largest hot desert (~9 million km²)."),
            ("IBPS conducts recruitment for which banks?",
             "Public sector banks (excluding SBI, which runs its own SBI PO/Clerk recruitment), Regional Rural Banks, and Specialist Officers."),
            ("Repo rate vs Reverse repo rate?",
             "Repo rate: the rate at which the RBI lends money to commercial banks. Reverse repo rate: the rate at which the RBI borrows from banks. Repo > Reverse repo."),
            ("Name two Group B Gazetted posts under SSC CGL.",
             "Assistant Audit Officer (CAG), Assistant Section Officer (CSS), Inspector (Income Tax / Central Excise), Sub-Inspector (CBI). Most senior is Assistant Audit / Accounts Officer."),
        ],
    },
]


def total_card_count() -> int:
    """Total number of starter cards across all decks."""
    return sum(len(d["cards"]) for d in STARTER_DECKS)
