"""prod-165 — Generate a ready-to-paste .env block for production.

Output is a copy-paste-able `.env` snippet with strong randomly
generated secrets for every variable the production-mode safeguards
in `padhai.auth._jwt_secret` would reject as a placeholder. Items
that genuinely require a human decision (real provider keys, the
actual production hostname, the Razorpay merchant ID) are left as
``TODO`` markers so they fail loudly if forgotten.

Usage::

    python scripts/generate_prod_secrets.py > production.env

Then audit `production.env`, fill in the TODO blocks, and copy the
result into your hosting platform's secret manager (Render/Vercel/
Fly/AWS Parameter Store). Never commit the resulting file — it
contains live credentials.

Exit codes:
    0 — secrets generated and printed
"""
from __future__ import annotations

import secrets
import sys

# UTF-8 stdout — the comments contain ₹ which crashes Windows cp1252.
if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass


def _gen(n: int = 48) -> str:
    """URL-safe random token. 48 bytes -> 64 chars of entropy; well above
    HS256's recommended 32-byte floor."""
    return secrets.token_urlsafe(n)


def emit() -> str:
    """Return the .env block as a single string."""
    lines = []
    add = lines.append
    add("# -----------------------------------------------------------------")
    add("# AI Pathshala production secrets")
    add("# Generated by scripts/generate_prod_secrets.py")
    add("# DO NOT commit this file. Paste into your secret manager.")
    add("# -----------------------------------------------------------------")
    add("")
    add("# Production mode — enables strict secret validation in auth.py.")
    add("APP_ENV=production")
    add("APP_BASE_URL=https://TODO_REPLACE_WITH_PROD_HOSTNAME.example.com")
    add("")
    add("# JWT signing secrets (HS256). Each 48 bytes -> 64 chars urlsafe.")
    add("# These rotate the bearer tokens of every signed-in user, so")
    add("# changing them logs everyone out. Rotate quarterly in prod.")
    add(f"PADHAI_JWT_SECRET={_gen(48)}")
    add(f"ADMIN_JWT_SECRET={_gen(48)}")
    add("")
    add("# Auth gate: 1 = required (production default).")
    add("PADHAI_REQUIRE_AUTH=1")
    add("")
    add("# Database — Postgres URL. Format:")
    add("#   postgresql://USER:PASSWORD@HOST:5432/DBNAME")
    add("# SQLite (single-server) is NOT acceptable for production load.")
    add("DATABASE_URL=postgresql://TODO_USER:TODO_PASSWORD@TODO_HOST:5432/padhai")
    add("")
    add("# Anthropic — generate at console.anthropic.com under API keys.")
    add("# Tier 2+ recommended for >100 DAU. Set budget alerts.")
    add("ANTHROPIC_API_KEY=TODO_REPLACE_sk-ant-...")
    add("")
    add("# Superuser admin emails (comma-separated). These accounts get")
    add("# the admin role without needing the DB flag flipped manually.")
    add("# REQUIRED in production — without this, the prod-mode safeguard")
    add("# in web.py lifespan refuses to boot.")
    add("PADHAI_SUPERUSER_EMAILS=TODO_admin@yourdomain.com")
    add("")
    add("# Admin console bootstrap. Set this ONCE to create the first")
    add("# admin via /admin/signup, then unset.")
    add(f"# ADMIN_BOOTSTRAP_TOKEN={_gen(32)}")
    add("")
    add("# -----------------------------------------------------------------")
    add("# SMTP — DPDP §9 parent-consent email channel. Without these,")
    add("# parent emails stall in the parent_consent_outbox table for an")
    add("# admin to manually process. Non-viable at scale.")
    add("# -----------------------------------------------------------------")
    add("SMTP_HOST=TODO_smtp.sendgrid.net_or_similar")
    add("SMTP_PORT=587")
    add("SMTP_USER=TODO_apikey")
    add("SMTP_PASS=TODO_secret")
    add("SMTP_FROM=TODO_no-reply@yourdomain.com")
    add("")
    add("# -----------------------------------------------------------------")
    add("# Razorpay — start in TEST mode, flip to live after first roundtrip.")
    add("# Webhook secret is set on the Razorpay dashboard webhook page.")
    add("# -----------------------------------------------------------------")
    add("RAZORPAY_KEY_ID=TODO_rzp_test_xxx")
    add("RAZORPAY_KEY_SECRET=TODO_secret")
    add(f"RAZORPAY_WEBHOOK_SECRET={_gen(32)}  # paste this into Razorpay dashboard")
    add("")
    add("# -----------------------------------------------------------------")
    add("# Observability")
    add("# -----------------------------------------------------------------")
    add("SENTRY_DSN=TODO_https://xxx@sentry.io/yyy")
    add("# PostHog (optional — analytics)")
    add("POSTHOG_API_KEY=TODO_phc_xxx")
    add("POSTHOG_HOST=https://app.posthog.com")
    add("")
    add("# Token gate for /__sentry_test in production (404s without).")
    add(f"PADHAI_SENTRY_TEST_TOKEN={_gen(24)}")
    add("")
    add("# -----------------------------------------------------------------")
    add("# Provider keys — fill in only what you actually use.")
    add("# Tiers M3/M4* require these; M1/M2 launch can leave them blank.")
    add("# -----------------------------------------------------------------")
    add("# HEYGEN_API_KEY=TODO_")
    add("# DID_API_KEY=TODO_")
    add("# TAVUS_API_KEY=TODO_")
    add("# ELEVENLABS_API_KEY=TODO_")
    add("# BHASHINI_API_KEY=TODO_")
    add("# SARVAM_API_KEY=TODO_")
    add("")
    add("# -----------------------------------------------------------------")
    add("# Cache + storage")
    add("# -----------------------------------------------------------------")
    add("# S3 / Cloudflare R2 — for production cache. Without these,")
    add("# the local-disk fallback is used (single-server only).")
    add("# S3_BUCKET=TODO")
    add("# S3_ENDPOINT_URL=https://TODO.r2.cloudflarestorage.com")
    add("# AWS_ACCESS_KEY_ID=TODO")
    add("# AWS_SECRET_ACCESS_KEY=TODO")
    add("")
    add("# -----------------------------------------------------------------")
    add("# Per-tier daily LLM cost caps (₹). M1 now carries a small ₹5/day")
    add("# free AI taste (PADHAI_M1_DAILY_CAP_PAISE, default 500 paise) — set")
    add("# it to 0 to revert to a hard paywall; higher tiers unlock more.")
    add("# These are calibrated against current model prices; revisit on")
    add("# model rename or material price change.")
    add("# Defaults match padhai/llm_obs.py DAILY_COST_CAPS_BY_TIER.")
    add("# -----------------------------------------------------------------")
    add("# (Leave these unset to use defaults.)")
    add("")
    add("# Mobile shells — what hostname the Capacitor builds point at.")
    add("CAPACITOR_SERVER_URL=https://TODO_REPLACE_WITH_PROD_HOSTNAME.example.com")
    add("")
    return "\n".join(lines) + "\n"


def main():
    out = emit()
    sys.stdout.write(out)
    sys.stderr.write(
        "\n# Generated. Audit + fill in TODOs before pasting into your\n"
        "# secret manager. Never commit the resulting file.\n",
    )


if __name__ == "__main__":
    main()
